## packages to install

## install libraries
install.packages("vip")
install.packages("gbm")
install.packages("klaR")
install.packages("xlsx")
install.packages("ROSE")
install.packages("readr")
install.packages("ipred")
install.packages("knitr")
install.packages("broom")
install.packages("purrr")
install.packages("rpart")
install.packages("ROCit")
install.packages("themis")
install.packages("glmnet")
install.packages("plotly")
install.packages("discrim")
install.packages("xgboost")
install.packages("foreach")
install.packages("ggplot2")
install.packages("corrplot")
install.packages("reshape2")
install.packages("tidyverse")
install.packages("tidymodels")
install.packages("data.table")
install.packages("rpart.plot")
install.packages("FactoMineR")
install.packages("factoextra")
install.packages("doParallel")
install.packages("randomForest")

## load libraries
library("gbm")
library("broom")
library("purrr")
library("glmnet")
library("ggplot2")
library("tidyverse")
library("tidymodels")
library("data.table")
library("FactoMineR")
library("factoextra")
library("randomForest")
