## packages to install

library("gbm")
library("vip")
library("ISLR")
library("repr")
library("xlsx")
library("embed")
library("rpart")
library("ipred") 
library("broom")
library("knitr")
library("dplyr")
library("e1071")
library("caret")
library("ROCit")
library("plotly")
library("themis")
library("glmnet")
library("kernlab")  
library("foreach")  
library("ggplot2")
library("xgboost")
library("kohonen")
library("corrplot")
library("reshape2")
library("tidyverse")
library("tidymodels")
library("data.table")
library("rpart.plot")
library("doParallel")
library("RColorBrewer")
library("randomForest")


